const accountID = 144553
let accountEmail = "khushi@google.com"
var accountPassword = "12345"
accountCity = "Jaipur"
let accountState;

//accountID = 2

accountEmail = "hc@hc.com"
accountPassword = "2121212121"
accountCity =  "Bengaluru"

console.log(accountID);

console.table([accountID, accountEmail, accountPassword, accountCity, accountState])

/*
Prefer not to use var
because of issue in block scope and functional scope
*/

